### Kinetic Energy 
### Get the estimated kinetic energy in Megaton TNT
### If an object of velocity 1 (km/s) and diameter 1 (km)
### is provided the result should be around 116 megaton. 
@rooturl = http://localhost:7071
GET {{rooturl}}/api/estimate/kineticenergy
Content-Type: application/json

{
    "id" : "{{$guid}}",
    "date" : "{{$datetime iso8601}}",
    "distance" : 5,
    "velocity" : 1,
    "diameter" : 1
}

### Impact Probability
GET {{rooturl}}/api/estimate/impactprobability
Content-Type: application/json

{
    "id" : "{{$guid}}",
    "date" : "{{$datetime iso8601}}",
    "distance" : 3,
    "velocity" : 1,
    "diameter" : 1
}