### Kinetic Energy 
### Get the estimated kinetic energy in Megaton TNT
### If an object of velocity 1 (km/s) and diameter 1 (km)
### is provided the result should be around 116 megaton. 
@id = {{$guid}}

# @name kineticRequest
@rooturl = http://localhost:7071
POST {{rooturl}}/api/estimate/kineticenergy
Content-Type: application/json

{
    "id" : "{{id}}",
    "date" : "{{$datetime iso8601}}",
    "distance" : 5,
    "velocity" : 30,
    "diameter" : 10
}

### Impact Probability
# @name impactRequest
POST {{rooturl}}/api/estimate/impactprobability
Content-Type: application/json

{
    "id" : "{{id}}",
    "date" : "{{$datetime iso8601}}",
    "distance" : 1,
    "velocity" : 1,
    "diameter" : 1
}

### Turino Impact
POST {{rooturl}}/api/estimate/torinoimpact
Content-Type: application/json

{
    "id" : "{{kineticRequest.response.body.$.id}}",
    "kinetic_energy_megaton_tnt" : {{kineticRequest.response.body.$.kinetic_energy_megaton_tnt}},
    "impact_probability" : {{impactRequest.response.body.$.impact_probability}}
}